In [1]:
import nltk
from nltk import tokenize
nltk.download('punkt') #checando se tenho o tokenizador!

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\barba\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [9]:
#segmentação de sentenças

sentencas = nltk.sent_tokenize(poema, language='portuguese')
print(sentencas)
print(len(sentencas))

['E agora, José?', 'A festa acabou,\na luz apagou,\no povo sumiu,\na noite esfriou,\ne agora, José?', 'e agora, você?', 'você que é sem nome,\nque zomba dos outros,\nvocê que faz versos,\nque ama, protesta?', 'e agora, José?', 'Está sem mulher,\nestá sem discurso,\nestá sem carinho,\njá não pode beber,\njá não pode fumar,\ncuspir já não pode,\na noite esfriou,\no dia não veio,\no bonde não veio,\no riso não veio,\nnão veio a utopia\ne tudo acabou\ne tudo fugiu\ne tudo mofou,\ne agora, José?', 'E agora, José?', 'Sua doce palavra,\nseu instante de febre,\nsua gula e jejum,\nsua biblioteca,\nsua lavra de ouro,\nseu terno de vidro,\nsua incoerência,\nseu ódio — e agora?', 'Com a chave na mão\nquer abrir a porta,\nnão existe porta;\nquer morrer no mar,\nmas o mar secou;\nquer ir para Minas,\nMinas não há mais.', 'José, e agora?', 'Se você gritasse,\nse você gemesse,\nse você tocasse\na valsa vienense,\nse você dormisse,\nse você cansasse,\nse você morresse...', 'Mas você não morre,\nvocê é 

In [27]:
#similaridade textual

import pandas as pd
import numpy as np

In [15]:
texts = ['Monkey D. Luffy is commonly known as "Straw Hat Luffy"! He is the founder and captain of the Straw Hat Pirates.',
         'He fearlessly pursues the legendary treasure of the late Gol D. Roger in order to become the new Pirate King.',
         'He believes that, by being the Pirate King, he will have the most freedom in the world.',
         'Edward Elric is a State Alchemist! He is given the official title of Fullmetal Alchemist.',
         'Like his brother, he is the victim of a failed Human Transmutation experiment to bring back their late mother.',
         'In an effort to restore their bodies to their original states, they set out on a quest to find the Philosopher\'s Stone.']
classes = ['One Piece', 'One Piece', 'One Piece', 'Fullmetal Alchemist', 'Fullmetal Alchemist', 'Fullmetal Alchemist']

df = pd.DataFrame({'texts': texts, 'classes': classes})
print(df)

                                               texts              classes
0  Monkey D. Luffy is commonly known as "Straw Ha...            One Piece
1  He fearlessly pursues the legendary treasure o...            One Piece
2  He believes that, by being the Pirate King, he...            One Piece
3  Edward Elric is a State Alchemist! He is given...  Fullmetal Alchemist
4  Like his brother, he is the victim of a failed...  Fullmetal Alchemist
5  In an effort to restore their bodies to their ...  Fullmetal Alchemist


In [17]:
#similaridade textual baseada em caracteres
#levenshtein: o valor da distância descreve o número mínimo de operações para transformar s em t

def levenshtein(seq1, seq2):
    # criar uma matriz
    size_x = len(seq1) + 1
    size_y = len(seq2) + 1
    matrix = np.zeros((size_x, size_y))

    # setar número das colunas (0, n-1)
    for x in range(size_x):
        matrix[x, 0] = x

    # setar número das linhas (0, n-1)
    for y in range(size_y):
        matrix[0, y] = y

    # calcular a distancia
    for x in range(1, size_x):
        for y in range(1, size_y):
            # se os caracteres são iguais, não aumenta distância
            if seq1[x-1] == seq2[y-1]:
                matrix[x, y] = matrix[x-1, y-1]
            # se são diferentes, aumenta a distância em 1
            else:
                matrix[x, y] = min(
                    matrix[x-1, y] + 1,
                    matrix[x-1, y-1] + 1,
                    matrix[x, y-1] + 1
                )

    #imprime a matriz de cálculo da distância
    #list(seq1) converte string em uma lista de caracteres
    print(pd.DataFrame(matrix[1:,1:], index=list(seq1), columns=list(seq2)))

    return (matrix[size_x - 1, size_y - 1])

In [18]:
levenshtein('medicina', 'medico') #exemplo menor de distância entre duas strings, só para testar

     m    e    d    i    c    o
m  0.0  1.0  2.0  3.0  4.0  5.0
e  1.0  0.0  1.0  2.0  3.0  4.0
d  2.0  1.0  0.0  1.0  2.0  3.0
i  3.0  2.0  1.0  0.0  1.0  2.0
c  4.0  3.0  2.0  1.0  0.0  1.0
i  5.0  4.0  3.0  2.0  1.0  1.0
n  6.0  5.0  4.0  3.0  2.0  2.0
a  7.0  6.0  5.0  4.0  3.0  3.0


np.float64(3.0)

In [19]:
#usando a distância de levenshtein para comparar textos

print(df)
print ("------")
doc_id_a = 3  # índice do texto 1
doc_id_b = 2  # índice do texto 2

print("texto 1: ", df.loc[doc_id_a]['texts'])
print("texto 2: ", df.loc[doc_id_b]['texts'])
print ("------")

levenshtein(df.loc[doc_id_a]['texts'], df.loc[doc_id_b]['texts'])

                                               texts              classes
0  Monkey D. Luffy is commonly known as "Straw Ha...            One Piece
1  He fearlessly pursues the legendary treasure o...            One Piece
2  He believes that, by being the Pirate King, he...            One Piece
3  Edward Elric is a State Alchemist! He is given...  Fullmetal Alchemist
4  Like his brother, he is the victim of a failed...  Fullmetal Alchemist
5  In an effort to restore their bodies to their ...  Fullmetal Alchemist
------
texto 1:  Edward Elric is a State Alchemist! He is given the official title of Fullmetal Alchemist.
texto 2:  He believes that, by being the Pirate King, he will have the most freedom in the world.
------
       H     e           b     e     l     i     e     v     e  ...     t  \
E    1.0   2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0  10.0  ...  78.0   
d    2.0   2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0  10.0  ...  77.0   
w    3.0   3.0   3.0   4.0   5.0   6.0 

np.float64(69.0)

In [32]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words('english'))
found_stopwords = set()

for text in texts:
    words = word_tokenize(text.lower())
    found_stopwords.update(word for word in words if word in stop_words)

print("Stopwords found in texts:", sorted(found_stopwords))

Stopwords found in texts: ['a', 'an', 'and', 'as', 'being', 'by', 'have', 'he', 'his', 'in', 'is', 'most', 'of', 'on', 'out', 'that', 'the', 'their', 'they', 'to', 'will']


In [50]:
#similaridade textual baseada em termos
#vetorizando os documentos de treinamento
#em outras palavras, transformando os textos em vetores em que as colunas são as palavras (sem stopwords)
#as linhas são a quantidade de vezes que um termo aparece nos textos (no mínimo 2)

import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

"""Criando o objeto vetorizador (convertendo para letras minúsculas, 
removendo as stopwords especificadas em uma lista e apenas mantendo 
os termos que ocorreram em dois ou mais documentos"""

vetorizador = CountVectorizer(
    lowercase=True,
    stop_words=['a', 'an', 'and', 'as', 'being', 'by', 'have', 'he', 'his', 
                'in', 'is', 'most', 'of', 'on', 'out', 'that', 'the', 'their', 
                'they', 'to', 'will'],
    min_df=2,
    dtype=np.int16
)

In [48]:
#obtendo o vocabulário

vetorizador.fit(df['texts'])
print(vetorizador.get_feature_names_out())

['king' 'late' 'pirate']


In [49]:
#gerando a representação estruturada a partir do vocabulário ajustado

representacao = vetorizador.transform(df['texts'])
print(representacao)

<Compressed Sparse Row sparse matrix of dtype 'int16'
	with 6 stored elements and shape (6, 3)>
  Coords	Values
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (2, 0)	1
  (2, 2)	1
  (4, 1)	1


In [51]:
#a representação retornada é uma matriz em formato esparso, mas é possível gerar o array

representacao
rep_array = representacao.toarray() #a partir daqui é possível aplicar funções de similaridade
print(rep_array)

[[0 0 0]
 [1 1 1]
 [1 0 1]
 [0 0 0]
 [0 1 0]
 [0 0 0]]


In [43]:
#cosseno é, também, uma forma de obter a similaridade entre textos

from sklearn.metrics.pairwise import cosine_similarity
matrix_sim = cosine_similarity(rep_array)

In [44]:
matrix_sim

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.81649658, 0.        , 0.57735027,
        0.        ],
       [0.        , 0.81649658, 1.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.57735027, 0.        , 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [45]:
def most_similar(id_doc, matrix): #função para buscar, dentre os textos, qual é o mais próximo de um parâmetro escolhido
    matrix_sim = cosine_similarity(matrix)
    best_sim = -1
    id_best_sim = -1;
    for id, doc_sim in enumerate(matrix_sim[id_doc]):
        if id != id_doc:
            if doc_sim > best_sim:
                best_sim = doc_sim
                id_best_sim = id
    return id_best_sim

In [52]:
print(df)
print ("------")
doc_id = 1 #parâmetro que eu escolhi
print('Texto: ', df.loc[doc_id]['texts'])
print('Texto mais parecido: ', df.loc[most_similar(doc_id, rep_array)]['texts'])

                                               texts              classes
0  Monkey D. Luffy is commonly known as "Straw Ha...            One Piece
1  He fearlessly pursues the legendary treasure o...            One Piece
2  He believes that, by being the Pirate King, he...            One Piece
3  Edward Elric is a State Alchemist! He is given...  Fullmetal Alchemist
4  Like his brother, he is the victim of a failed...  Fullmetal Alchemist
5  In an effort to restore their bodies to their ...  Fullmetal Alchemist
------
Texto:  He fearlessly pursues the legendary treasure of the late Gol D. Roger in order to become the new Pirate King.
Texto mais parecido:  He believes that, by being the Pirate King, he will have the most freedom in the world.


In [53]:
#mais uma métrica de similaridade baseada em termos: jaccard

from sklearn.metrics.pairwise import pairwise_distances

def most_similar(id_doc, matrix):
    matrix_sim = 1 - pairwise_distances(matrix, metric='jaccard') # como é medida de distância (valor entre 0 e 1), utilizar o complemento
    best_sim = -1
    id_best_sim = -1
    for id, doc_sim in enumerate(matrix_sim[id_doc]):
        if id != id_doc:
            if doc_sim > best_sim:
                best_sim = doc_sim
                id_best_sim = id
    return id_best_sim

In [54]:
matrix_sim = 1 - pairwise_distances(rep_array, metric='jaccard')
matrix_sim

C:\Users\barba\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\pairwise.py:2466: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)


array([[1.        , 0.        , 0.        , 1.        , 0.        ,
        1.        ],
       [0.        , 1.        , 0.66666667, 0.        , 0.33333333,
        0.        ],
       [0.        , 0.66666667, 1.        , 0.        , 0.        ,
        0.        ],
       [1.        , 0.        , 0.        , 1.        , 0.        ,
        1.        ],
       [0.        , 0.33333333, 0.        , 0.        , 1.        ,
        0.        ],
       [1.        , 0.        , 0.        , 1.        , 0.        ,
        1.        ]])

In [56]:
import warnings
warnings.filterwarnings('ignore')

print(df)
print('------')
doc_id = 1
print('Texto: ', df.loc[doc_id]['texts'])
print('Texto mais parecido: ', df.loc[most_similar(doc_id, rep_array)]['texts'])

                                               texts              classes
0  Monkey D. Luffy is commonly known as "Straw Ha...            One Piece
1  He fearlessly pursues the legendary treasure o...            One Piece
2  He believes that, by being the Pirate King, he...            One Piece
3  Edward Elric is a State Alchemist! He is given...  Fullmetal Alchemist
4  Like his brother, he is the victim of a failed...  Fullmetal Alchemist
5  In an effort to restore their bodies to their ...  Fullmetal Alchemist
------
Texto:  He fearlessly pursues the legendary treasure of the late Gol D. Roger in order to become the new Pirate King.
Texto mais parecido:  He believes that, by being the Pirate King, he will have the most freedom in the world.


In [59]:
from sklearn.metrics import jaccard_score  # alternativa para comparar 2 textos / vetores

doc_id_a = 1
doc_id_b = 4
textol = rep_array[doc_id_a]
texto2 = rep_array[doc_id_b]

print(textol)
print(texto2)
jaccard_score(textol, texto2)

[1 1 1]
[0 1 0]


np.float64(0.3333333333333333)

In [60]:
#por fim, euclidiana

def most_similar(id_doc, matrix):
    matrix_sim = pairwise_distances(matrix, metric='euclidean')
    best_sim = 99999999
    id_best_sim = -1
    for id, doc_sim in enumerate(matrix_sim[id_doc]):
        if id != id_doc:
            if doc_sim <= best_sim:
                best_sim = doc_sim
                id_best_sim = id
    return id_best_sim

In [62]:
matrix_sim = pairwise_distances(rep_array, metric='euclidean')
matrix_sim

array([[0.        , 1.73205081, 1.41421356, 0.        , 1.        ,
        0.        ],
       [1.73205081, 0.        , 1.        , 1.73205081, 1.41421356,
        1.73205081],
       [1.41421356, 1.        , 0.        , 1.41421356, 1.73205081,
        1.41421356],
       [0.        , 1.73205081, 1.41421356, 0.        , 1.        ,
        0.        ],
       [1.        , 1.41421356, 1.73205081, 1.        , 0.        ,
        1.        ],
       [0.        , 1.73205081, 1.41421356, 0.        , 1.        ,
        0.        ]])

In [63]:
print(df)
print('------')
doc_id = 1
print('Texto: ', df.loc[doc_id]['texts'])
print('Texto mais parecido: ', df.loc[most_similar(doc_id, rep_array)]['texts'])

                                               texts              classes
0  Monkey D. Luffy is commonly known as "Straw Ha...            One Piece
1  He fearlessly pursues the legendary treasure o...            One Piece
2  He believes that, by being the Pirate King, he...            One Piece
3  Edward Elric is a State Alchemist! He is given...  Fullmetal Alchemist
4  Like his brother, he is the victim of a failed...  Fullmetal Alchemist
5  In an effort to restore their bodies to their ...  Fullmetal Alchemist
------
Texto:  He fearlessly pursues the legendary treasure of the late Gol D. Roger in order to become the new Pirate King.
Texto mais parecido:  He believes that, by being the Pirate King, he will have the most freedom in the world.
